#!/usr/bin/env python3
"""
Popola MetaBorghi_DataTemplate.xlsx con i dati delle aziende
attualmente presenti nella piattaforma (companies-DS8bqSy6.js).
"""

import openpyxl
from copy import copy

EXCEL_PATH = "MetaBorghi_DataTemplate.xlsx"

# Dati aziende estratti da companies-DS8bqSy6.js
companies = [
    {
        "id": "deleo-carni",
        "slug": "deleo-carni",
        "name": "De Leo Carni",
        "legal_name": "De Leo Carni S.r.l.",
        "vat_number": "IT02345678901",
        "founding_year": 1968,
        "employees_count": 12,
        "founder_name": "Antonio De Leo",
        "founder_quote": "Ogni salume racconta la storia della nostra terra e del nostro lavoro.",
        "borough_id": "nusco",
        "address_full": "Via Roma 45, 83051 Nusco (AV)",
        "coordinates_lat": 40.888,
        "coordinates_lng": 15.09,
        "type": "PRODUTTORE_FOOD",
        "tagline": "La tradizione norcina dell'Alta Irpinia",
        "description_short": "Salumi artigianali irpini prodotti secondo le antiche ricette di famiglia.",
        "description_long": "Da oltre tre generazioni, De Leo Carni custodisce i segreti della norcineria irpina. Ogni salume nasce dalla selezione accurata delle carni di suini allevati allo stato semibrado nelle colline dell'Alta Irpinia, nutrendosi di ghiande e castagne. La lavorazione avviene ancora a mano, con la stagionatura naturale nelle cantine in tufo che garantiscono il microclima perfetto per esaltare i sapori autentici del territorio.",
        "certifications": "BIO, Slow Food",
        "awards": "2023 - Miglior Soppressata d'Italia - Slow Food",
        "tier": "PREMIUM",
        "contact_email": "info@deleocarni.com",
        "contact_phone": "+39 0827 64521",
        "website_url": "https://www.deleocarni.com",
        "social_instagram": "#",
        "social_facebook": "#",
        "main_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "virtual_tour_url": "https://www.google.com/maps/embed?pb=!4v1700000000000!6m8!1m7!1sCAoSLEFGMVFpcE5fX0JQX3RhbWVfY2FrRXdJOXJIeHFYVWNZb2JtVXdMbTBw!2m2!1d40.888!2d15.090!3f0!4f0!5f0.7820865974627469",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Distribuzione, Ristorazione, Gift box",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "contedoro",
        "slug": "contedoro",
        "name": "Conte d'Oro",
        "legal_name": "Conte d'Oro S.a.s.",
        "vat_number": "IT03456789012",
        "founding_year": 1952,
        "employees_count": 8,
        "founder_name": "Maria Conte",
        "founder_quote": "L'olio buono si fa in campo, non in frantoio. Il frantoio lo completa.",
        "borough_id": "guardia-dei-lombardi",
        "address_full": "Contrada Oliveto 12, 83040 Guardia dei Lombardi (AV)",
        "coordinates_lat": 40.957,
        "coordinates_lng": 15.198,
        "type": "PRODUTTORE_FOOD",
        "tagline": "L'oro verde dell'Irpinia",
        "description_short": "Olio extravergine d'oliva DOP dalle colline irpine.",
        "description_long": "Conte d'Oro è un frantoio familiare che produce olio extravergine d'oliva dalle cultivar autoctone dell'Irpinia: Ravece, Ogliarola e Marinese. Gli uliveti si estendono sulle colline di Guardia dei Lombardi, dove il clima e l'altitudine conferiscono all'olio note fruttate intense e un retrogusto leggermente piccante. La molitura avviene entro 24 ore dalla raccolta, a freddo, per preservare ogni proprietà organolettica.",
        "certifications": "DOP, BIO",
        "awards": "2024 - Gran Menzione Olio DOP - Ercole Olivario",
        "tier": "PREMIUM",
        "contact_email": "info@contedoro.com",
        "contact_phone": "+39 0827 41023",
        "website_url": "https://contedoro.com",
        "social_instagram": "#",
        "social_facebook": "#",
        "main_video_url": "",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Export, Ristorazione, Co-branding",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "boccella-rosa",
        "slug": "boccella-rosa",
        "name": "Boccella Rosa",
        "legal_name": "Boccella Rosa Azienda Vinicola",
        "vat_number": "IT04567890123",
        "founding_year": 1985,
        "employees_count": 15,
        "founder_name": "Giovanni Boccella",
        "founder_quote": "Il Taurasi è un vino che ha bisogno di tempo. Come le cose migliori.",
        "borough_id": "castelfranci",
        "address_full": "Contrada Vigne 8, 83040 Castelfranci (AV)",
        "coordinates_lat": 40.93,
        "coordinates_lng": 15.04,
        "type": "PRODUTTORE_FOOD",
        "tagline": "Vini d'Irpinia, anima di vulcano",
        "description_short": "Vini irpini d'eccellenza: Taurasi, Fiano e Greco di Tufo.",
        "description_long": "Boccella Rosa nasce dalla passione di una famiglia di viticoltori che da generazioni coltiva i vitigni autoctoni dell'Irpinia. I vigneti di Aglianico, Fiano e Greco crescono su terreni vulcanici a 500 metri di altitudine, dove le escursioni termiche e i venti montani regalano uve di straordinaria intensità. La vinificazione rispetta i ritmi naturali, con lunghi affinamenti in botti di rovere e in bottiglia.",
        "certifications": "DOCG, DOC, BIO",
        "awards": "2024 - Tre Bicchieri - Gambero Rosso | 2023 - 95 punti Taurasi Riserva - Wine Spectator",
        "tier": "PLATINUM",
        "contact_email": "info@boccellarosa.it",
        "contact_phone": "+39 0827 72145",
        "website_url": "https://boccellarosa.it",
        "social_instagram": "#",
        "social_facebook": "#",
        "main_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Export, Distribuzione, Enoteca, Ristorazione",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "re-del-bosco",
        "slug": "re-del-bosco",
        "name": "Re del Bosco",
        "legal_name": "Re del Bosco S.r.l.",
        "vat_number": "IT05678901234",
        "founding_year": 1990,
        "employees_count": 20,
        "founder_name": "Luigi Montella",
        "founder_quote": "Ogni castagna porta con sé il profumo del bosco e la pazienza dei nostri nonni.",
        "borough_id": "montella",
        "address_full": "Via dei Castagneti 22, 83048 Montella (AV)",
        "coordinates_lat": 40.843,
        "coordinates_lng": 15.017,
        "type": "PRODUTTORE_FOOD",
        "tagline": "Le castagne più pregiate d'Italia",
        "description_short": "Castagna di Montella IGP e derivati dal cuore dei Picentini.",
        "description_long": "Re del Bosco raccoglie e trasforma la Castagna di Montella IGP, una delle eccellenze più riconosciute della Campania. I castagneti secolari dei Monti Picentini, tra Montella e Bagnoli Irpino, producono frutti di dimensioni generose e sapore dolcissimo. Dall'essiccatura tradizionale nei \"gratali\" alla farina di castagne macinata a pietra, ogni prodotto preserva il gusto autentico del bosco irpino.",
        "certifications": "IGP, BIO",
        "awards": "2024 - Premio Eccellenza IGP - Qualivita",
        "tier": "PREMIUM",
        "contact_email": "info@redelbosco.it",
        "contact_phone": "+39 0827 61234",
        "website_url": "https://www.redelbosco.it",
        "social_instagram": "#",
        "social_facebook": "#",
        "main_video_url": "",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Distribuzione, Pasticceria, Export",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "serrocroce",
        "slug": "serrocroce",
        "name": "Serrocroce",
        "legal_name": "Serrocroce Azienda Agricola",
        "vat_number": "IT06789012345",
        "founding_year": 2005,
        "employees_count": 6,
        "founder_name": "Marco Serra",
        "founder_quote": "Il vino naturale non si fa, si lascia fare. Noi ascoltiamo la vigna.",
        "borough_id": "castelfranci",
        "address_full": "Contrada Serrocroce, 83040 Castelfranci (AV)",
        "coordinates_lat": 40.935,
        "coordinates_lng": 15.045,
        "type": "PRODUTTORE_FOOD",
        "tagline": "Vini naturali dall'Alta Irpinia",
        "description_short": "Vini naturali biodinamici da vigneti d'alta quota.",
        "description_long": "Serrocroce è una cantina boutique che pratica viticoltura biodinamica sui terreni vulcanici dell'Alta Irpinia. I vigneti, coltivati a 600 metri sul livello del mare, producono vini di grande personalità: minerali, freschi, con una complessità aromatica che racconta il territorio. La cantina è scavata nel tufo, dove i vini riposano in anfore di terracotta e botti di castagno locale.",
        "certifications": "BIO, DOC",
        "awards": "2024 - Vino Naturale dell'Anno - Guida Slow Wine",
        "tier": "BASE",
        "contact_email": "info@serrocroce.it",
        "contact_phone": "+39 0827 72098",
        "website_url": "https://www.serrocroce.it",
        "social_instagram": "#",
        "social_facebook": "",
        "main_video_url": "",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Enoteca, Ristorazione, Export",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "caciocavalleria",
        "slug": "caciocavalleria",
        "name": "Caciocavalleria De D.",
        "legal_name": "Caciocavalleria De D. S.a.s.",
        "vat_number": "IT07890123456",
        "founding_year": 1975,
        "employees_count": 10,
        "founder_name": "Paolo De Dominicis",
        "founder_quote": "Le nostre vacche Podoliche camminano libere. Il formaggio che producono non ha eguali.",
        "borough_id": "lacedonia",
        "address_full": "Contrada Masseria 5, 83046 Lacedonia (AV)",
        "coordinates_lat": 41.05,
        "coordinates_lng": 15.42,
        "type": "PRODUTTORE_FOOD",
        "tagline": "Il re dei formaggi irpini",
        "description_short": "Caciocavallo Podolico e formaggi di latte crudo dall'Irpinia.",
        "description_long": "La Caciocavalleria De D. è un caseificio artigianale specializzato nella produzione di Caciocavallo Podolico, ottenuto dal latte delle vacche Podoliche allevate al pascolo brado sui pascoli dell'Alta Irpinia. Questo formaggio raro, prodotto solo con latte di razza autoctona, viene stagionato per un minimo di 12 mesi nelle grotte naturali. Il risultato è un formaggio dal gusto intenso, leggermente piccante, con sentori di erbe selvatiche.",
        "certifications": "Slow Food, De.Co.",
        "awards": "2023 - Presidio Slow Food - Slow Food Italia",
        "tier": "PREMIUM",
        "contact_email": "info@caciocavalleriaded.it",
        "contact_phone": "+39 0827 85012",
        "website_url": "https://www.caciocavalleriaded.it",
        "social_instagram": "#",
        "social_facebook": "#",
        "main_video_url": "",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Distribuzione, Ristorazione, Export",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "carmasciando",
        "slug": "carmasciando",
        "name": "Carmasciando",
        "legal_name": "Carmasciando Azienda Agricola",
        "vat_number": "IT08901234567",
        "founding_year": 2010,
        "employees_count": 8,
        "founder_name": "Salvatore Carmasciando",
        "founder_quote": "Il vino è solo l'inizio. Venite a vivere questa terra.",
        "borough_id": "torella-dei-lombardi",
        "address_full": "Contrada Piano 15, 83057 Torella dei Lombardi (AV)",
        "coordinates_lat": 40.94,
        "coordinates_lng": 15.113,
        "type": "MISTO",
        "tagline": "Vino, terra, accoglienza",
        "description_short": "Cantina con agriturismo e esperienze nel cuore dell'Irpinia.",
        "description_long": "Carmasciando è un progetto di vita che unisce viticoltura, ospitalità e cultura del territorio. La cantina produce vini da vitigni autoctoni irpini, mentre l'agriturismo offre esperienze immersive: dalle vendemmie partecipate alle cene in vigna, dalla raccolta delle olive ai laboratori di cucina irpina. Un luogo dove il tempo rallenta e i sapori raccontano storie.",
        "certifications": "BIO, DOC",
        "awards": "",
        "tier": "PLATINUM",
        "contact_email": "info@carmasciando.it",
        "contact_phone": "+39 0827 49876",
        "website_url": "https://carmasciando.it",
        "social_instagram": "#",
        "social_facebook": "#",
        "main_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "virtual_tour_url": "https://www.google.com/maps/embed?pb=!4v1700000000000!6m8!1m7!1sCAoSLEFGMVFpcE5fX0JQX3RhbWVfY2FrRXdJOXJIeHFYVWNZb2JtVXdMbTBw!2m2!1d40.940!2d15.113!3f0!4f0!5f0.7820865974627469",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Turismo, Ristorazione, Eventi, Co-branding",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "torronificio-del-casale",
        "slug": "torronificio-del-casale",
        "name": "Torronificio del Casale",
        "legal_name": "Torronificio del Casale S.r.l.",
        "vat_number": "IT09012345678",
        "founding_year": 1890,
        "employees_count": 18,
        "founder_name": "Rosa Del Casale",
        "founder_quote": "Il segreto del nostro torrone? Il tempo. Non abbiamo mai avuto fretta.",
        "borough_id": "sant-angelo-dei-lombardi",
        "address_full": "Via Mancini 8, 83054 Sant'Angelo dei Lombardi (AV)",
        "coordinates_lat": 40.927,
        "coordinates_lng": 15.175,
        "type": "PRODUTTORE_FOOD",
        "tagline": "L'arte del torrone dal 1890",
        "description_short": "Torroni artigianali irpini: miele, nocciole e tradizione.",
        "description_long": "Il Torronificio del Casale porta avanti una tradizione dolciaria che risale alla fine dell'Ottocento. Il torrone viene prodotto con miele di castagno dell'Irpinia, nocciole Tonde di Giffoni e mandorle selezionate, seguendo il metodo di cottura lenta in caldaie di rame. Ogni barretta è confezionata a mano, come si faceva un tempo. Una dolcezza autentica che racconta la storia del Natale irpino.",
        "certifications": "De.Co., Slow Food",
        "awards": "2024 - Eccellenza Artigiana - CNA Campania",
        "tier": "PREMIUM",
        "contact_email": "info@torronificiodelcasale.com",
        "contact_phone": "+39 0827 23456",
        "website_url": "https://www.torronificiodelcasale.com",
        "social_instagram": "#",
        "social_facebook": "#",
        "main_video_url": "",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Distribuzione, Gift box, Export, HoReCa",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "dolci-terre",
        "slug": "dolci-terre",
        "name": "Dolci Terre",
        "legal_name": "Dolci Terre di Irpinia",
        "vat_number": "IT10123456789",
        "founding_year": 2008,
        "employees_count": 5,
        "founder_name": "Francesca Iannaccone",
        "founder_quote": "La natura ci regala tutto. Noi lo mettiamo in un vasetto.",
        "borough_id": "montella",
        "address_full": "Via Fontana 30, 83048 Montella (AV)",
        "coordinates_lat": 40.845,
        "coordinates_lng": 15.02,
        "type": "PRODUTTORE_FOOD",
        "tagline": "La dolcezza autentica dell'Irpinia",
        "description_short": "Confetture, mieli e conserve dal cuore verde dell'Irpinia.",
        "description_long": "Dolci Terre trasforma i frutti spontanei e coltivati dell'Alta Irpinia in confetture, mieli aromatici e conserve. Dalle fichi tardive ai pomodori secchi, dal miele di castagno a quello millefiori di montagna: ogni vasetto è il risultato di una filiera cortissima, dalla pianta al prodotto finito in meno di 48 ore. Senza conservanti, senza coloranti, solo il sapore vero della terra.",
        "certifications": "BIO",
        "awards": "",
        "tier": "BASE",
        "contact_email": "info@dolciterre.it",
        "contact_phone": "+39 0827 61890",
        "website_url": "https://www.dolciterre.it",
        "social_instagram": "#",
        "social_facebook": "",
        "main_video_url": "",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "NO",
        "b2b_interests": "",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "tenuta-pepe",
        "slug": "tenuta-pepe",
        "name": "Tenuta Pepe",
        "legal_name": "Tenuta Pepe S.a.s.",
        "vat_number": "IT11234567890",
        "founding_year": 1986,
        "employees_count": 12,
        "founder_name": "Roberto Pepe",
        "founder_quote": "L'Irpinia è la Borgogna del Sud. I nostri vini lo dimostrano.",
        "borough_id": "lioni",
        "address_full": "Contrada Vigne 5, 83047 Lioni (AV)",
        "coordinates_lat": 40.878,
        "coordinates_lng": 15.183,
        "type": "PRODUTTORE_FOOD",
        "tagline": "Tradizione vinicola dal 1986",
        "description_short": "Vini d'autore dall'Irpinia: Taurasi DOCG e Fiano di Avellino.",
        "description_long": "Tenuta Pepe è una delle cantine storiche dell'Irpinia, fondata nel 1986 dalla famiglia Pepe con l'obiettivo di valorizzare i grandi vitigni autoctoni campani. I vigneti si estendono su 15 ettari di terreni argilloso-calcarei, ideali per l'Aglianico e il Fiano. La cantina combina metodi tradizionali con tecnologia enologica moderna, producendo vini eleganti che esprimono il terroir irpino.",
        "certifications": "DOCG, DOC, BIO",
        "awards": "2024 - Tre Bicchieri Taurasi - Gambero Rosso | 2023 - 93 punti Fiano - James Suckling",
        "tier": "PLATINUM",
        "contact_email": "info@tenutapepe.it",
        "contact_phone": "+39 0827 42567",
        "website_url": "https://www.tenutapepe.it",
        "social_instagram": "#",
        "social_facebook": "#",
        "main_video_url": "",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Export, Enoteca, Ristorazione, Hotel",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "sella-delle-spine",
        "slug": "sella-delle-spine",
        "name": "Sella delle Spine",
        "legal_name": "Sella delle Spine Azienda Agricola",
        "vat_number": "IT12345678901",
        "founding_year": 1998,
        "employees_count": 4,
        "founder_name": "Anna Spinelli",
        "founder_quote": "Il Greco di Tufo è la voce della terra vulcanica. Noi lo lasciamo parlare.",
        "borough_id": "calitri",
        "address_full": "Contrada Spine 3, 83045 Calitri (AV)",
        "coordinates_lat": 40.9,
        "coordinates_lng": 15.44,
        "type": "PRODUTTORE_FOOD",
        "tagline": "Dove nasce il Greco di Tufo",
        "description_short": "Greco di Tufo DOCG e bianchi d'alta quota.",
        "description_long": "Sella delle Spine è una piccola cantina familiare che coltiva Greco di Tufo sui pendii vulcanici dell'Irpinia. I vigneti, esposti a sud-est, beneficiano delle brezze montane e delle escursioni termiche che conferiscono al Greco una freschezza e una mineralità uniche. La produzione è volutamente limitata per garantire la massima qualità in ogni bottiglia.",
        "certifications": "DOCG, BIO",
        "awards": "",
        "tier": "BASE",
        "contact_email": "info@selladellespine.com",
        "contact_phone": "+39 0827 35012",
        "website_url": "https://www.selladellespine.com",
        "social_instagram": "#",
        "social_facebook": "",
        "main_video_url": "",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Enoteca, Export",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "bifulco",
        "slug": "bifulco",
        "name": "Bifulco",
        "legal_name": "Bifulco Alimentari S.r.l.",
        "vat_number": "IT13456789012",
        "founding_year": 1972,
        "employees_count": 9,
        "founder_name": "Carlo Bifulco",
        "founder_quote": "La pasta buona si riconosce dal profumo del grano, non dall'etichetta.",
        "borough_id": "lioni",
        "address_full": "Via Industria 18, 83047 Lioni (AV)",
        "coordinates_lat": 40.88,
        "coordinates_lng": 15.185,
        "type": "PRODUTTORE_FOOD",
        "tagline": "Pasta e tradizione irpina",
        "description_short": "Pasta artigianale e prodotti da forno della tradizione irpina.",
        "description_long": "Bifulco è un pastificio artigianale che produce pasta di semola di grano duro con trafilatura al bronzo e essiccazione lenta. I fusilli al ferretto, i cavatelli e le lagane sono le specialità della casa, preparate con lo stesso metodo che le massaie irpine usano da secoli. Il grano proviene dalle campagne dell'Alta Irpinia, macinato in piccoli mulini locali.",
        "certifications": "De.Co.",
        "awards": "",
        "tier": "BASE",
        "contact_email": "info@bifulco.it",
        "contact_phone": "+39 0827 42890",
        "website_url": "https://www.bifulco.it",
        "social_instagram": "",
        "social_facebook": "#",
        "main_video_url": "",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Distribuzione, Ristorazione",
        "is_verified": "SI",
        "is_active": "SI",
    },
    {
        "id": "akudunniad",
        "slug": "akudunniad",
        "name": "A' Ku Dunniad",
        "legal_name": "A' Ku Dunniad Cooperativa Sociale",
        "vat_number": "IT14567890123",
        "founding_year": 2015,
        "employees_count": 14,
        "founder_name": "Teresa Calitri",
        "founder_quote": "Restare è la forma più coraggiosa di innovazione.",
        "borough_id": "calitri",
        "address_full": "Via del Borgo 7, 83045 Calitri (AV)",
        "coordinates_lat": 40.895,
        "coordinates_lng": 15.435,
        "type": "MISTO",
        "tagline": "Il sapore della comunità",
        "description_short": "Cooperativa sociale: prodotti tipici, ospitalità e inclusione.",
        "description_long": "A' Ku Dunniad (dal dialetto irpino \"come una volta\") è una cooperativa sociale che unisce produzione agroalimentare, turismo responsabile e inclusione sociale. I prodotti — conserve, confetture, pasta fresca — nascono dal lavoro di una comunità che ha scelto di restare e innovare nei borghi dell'Alta Irpinia. Un modello di economia circolare e sostenibile.",
        "certifications": "BIO",
        "awards": "2023 - Premio Innovazione Sociale - Ashoka Italia",
        "tier": "PREMIUM",
        "contact_email": "info@akudunniad.it",
        "contact_phone": "+39 0827 35890",
        "website_url": "https://akudunniad.it",
        "social_instagram": "#",
        "social_facebook": "#",
        "main_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "virtual_tour_url": "",
        "b2b_open_for_contact": "SI",
        "b2b_interests": "Turismo, Inclusione sociale, Distribuzione",
        "is_verified": "SI",
        "is_active": "SI",
    },
]

# Ordine colonne (riga 2 dell'Excel)
COLUMNS = [
    "id", "slug", "name", "legal_name", "vat_number",
    "founding_year", "employees_count", "founder_name", "founder_quote",
    "borough_id", "address_full", "coordinates_lat", "coordinates_lng",
    "type", "tagline", "description_short", "description_long",
    "certifications", "awards", "tier",
    "contact_email", "contact_phone", "website_url",
    "social_instagram", "social_facebook",
    "main_video_url", "virtual_tour_url",
    "b2b_open_for_contact", "b2b_interests",
    "is_verified", "is_active",
]

def populate():
    wb = openpyxl.load_workbook(EXCEL_PATH)
    ws = wb["Aziende"]

    # Riga 3 = istruzioni, i dati partono dalla riga 4
    start_row = 4

    for r_idx, company in enumerate(companies):
        row_num = start_row + r_idx
        for c_idx, col_key in enumerate(COLUMNS):
            col_num = c_idx + 1  # openpyxl è 1-indexed
            value = company.get(col_key, "")
            ws.cell(row=row_num, column=col_num, value=value)

    wb.save(EXCEL_PATH)
    print(f"✅ Popolate {len(companies)} aziende nel foglio 'Aziende' a partire dalla riga {start_row}.")
    print("📄 File salvato:", EXCEL_PATH)

if __name__ == "__main__":
    populate()
